name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        APP_PATH: ${{ secrets.APP_PATH }}
        REPO_URL: ${{ secrets.REPO_URL }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP "
        if [ ! -d '$APP_PATH' ]; then
          mkdir -p $APP_PATH
          echo 'Cloning repository...'
          git clone $REPO_URL $APP_PATH || { echo 'Git clone failed'; exit 1; }
        fi
        cd $APP_PATH &&
        git pull origin main || { echo 'Git pull failed'; exit 1; }
        npm install || { echo 'NPM install failed'; exit 1; }
        pm2 restart all || pm2 start npm --name 'app' -- start || { echo 'PM2 restart/start failed'; exit 1; }
        echo 'Deployment complete.'
      "
